# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cont_ks_distribution_Rcpp <- function(n) {
    .Call(`_ksgeneral_cont_ks_distribution_Rcpp`, n)
}

cont_ks_distribution_Rcpp_alternative <- function(n, x) {
    .Call(`_ksgeneral_cont_ks_distribution_Rcpp_alternative`, n, x)
}

